# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwokDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 4.0'
pod 'Toast', '~> 4.0.0'
pod 'MMMaterialDesignSpinner'

  # Pods for AwokDemoApp

  target 'AwokDemoAppTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'AwokDemoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
